DROP TABLE IF EXISTS BC_DEMO;
DROP SEQUENCE IF EXISTS BC_DEMO_SEQ;
CREATE TABLE IF NOT EXISTS BC_DEMO
(
    DE_ID numeric(38, 0) NOT NULL,
    DE_UUID uuid NOT NULL,
    DE_CODE VARCHAR(20) NOT NULL,
    DE_NAME VARCHAR(30) NOT NULL,
    CONSTRAINT BC_DEMO_PK PRIMARY KEY (DE_ID),
    CONSTRAINT BC_DEMO_UN_UUID UNIQUE (DE_UUID),
    CONSTRAINT BC_DEMO_UN_CODE UNIQUE (DE_CODE),
    CONSTRAINT BC_DEMO_NN1 CHECK ( DE_NAME IS NOT NULL)
);

CREATE SEQUENCE IF NOT EXISTS BC_DEMO_SEQ
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 99999999999999999
    START 1;
